AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvironmentName:
    Type: String

  VpcId:
    Type: String

  PrivateSubnetIds:
    Type: String

  PublicSubnetIds:
    Type: String


Resources:
  WebsiteApiServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - elasticbeanstalk.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService

  WebsiteApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

  WebsiteApiPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: App
      Roles:
      - !Ref WebsiteApiRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"

  WebsiteApiInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref WebsiteApiRole

  WebsiteApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${EnvironmentName}-website-api-http-ingress-sg'
      GroupDescription: !Sub '${EnvironmentName} WebsiteApi Security group to HTTP to allow connect'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  WebsiteApiApp:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: WebSiteApi Beanstalk App

  WebsiteApiAppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref WebsiteApiApp
      Description: WebSiteApi Beanstalk App Version
      SourceBundle:
        S3Bucket: _ARTIFACT_BUCKET_
        S3Key: website-api/code._COMMIT_.zip

  WebsiteApiConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref WebsiteApiApp
      Description: WebSiteApi Beanstalk App Configuration Template
      SolutionStackName: 64bit Amazon Linux 2 v3.1.2 running Python 3.7
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced

        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref WebsiteApiServiceRole

        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref WebsiteApiInstanceProfile

        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: "1"

        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: "2"

        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: StreamLogs
          Value: "true"

        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: DeleteOnTerminate
          Value: "true"

        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !Ref VpcId

        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !Ref PrivateSubnetIds

        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: !Ref PublicSubnetIds

        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Ref WebsiteApiSecurityGroup

  WebsiteApiEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      Description: WebSiteApi Beanstalk App Environment
      ApplicationName: !Ref WebsiteApiApp
      TemplateName: !Ref WebsiteApiConfigurationTemplate
      VersionLabel: !Ref WebsiteApiAppVersion
